# -*- coding: utf-8 -*-
"""ml2plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q4ykgmUBlRt7CBjcGrE89F5KLG82cFt_
"""

import matplotlib.pyplot as plt
x_days=[1,2,3,4,5]
y_price=[3,8.9,4,6,7]
y_price1=[0.9,5,7.8,2,4.5]
plt.title("stock movement")
plt.xlabel("week days")
plt.ylabel("price in usd")
 
plt.plot(x_days,y_price,label="stock1")
plt.plot(x_days,y_price1,label="stock2")
plt.legend(loc="upper right",fontsize=10)



import matplotlib.pyplot as plt

file=open('/content/drive/MyDrive/datasheet/agedata.csv - agedata.csv.csv','r')
a=file.readlines()


age_list=[]

for handle in a:
  age_list.append(int(handle))

bins=[0,10,20,30,40,50,60,70,80,90,100]

plt.title("Histogram")
plt.xlabel("age group")
plt.ylabel("age")

plt.hist(age_list,bins,histtype='bar',rwidth=0.9)
plt.show()

import matplotlib.pyplot as plt

cities=['london','newyork','delhi','berlin']
temp=[60,78,90,73]


plt.title("Temperature plot")
plt.xlabel("cities")
plt.ylabel("temperature")
plt.grid(True)
plt.bar(cities,temp,width=0.5)
plt.show()

import matplotlib.pyplot as plt


file=open('/content/drive/MyDrive/datasheet/salesdata.csv - salesdata.csv.csv','r')
data = file.readlines()
lst=[]
for handle in data:
  lst.append(int(handle))
plt.title("box plot")
plt.boxplot(lst) 
plt.show()

x = [1,1,2,3,3,5,7,8,9,10,
     10,11,11,13,13,15,16,17,18,18,
     18,19,20,21,21,23,24,24,25,25,
     25,25,26,26,26,27,27,27,27,27,
     29,30,30,31,33,34,34,34,35,36,
     36,37,37,38,38,39,40,41,41,42,
     43,44,45,45,46,47,48,48,49,50,
     51,52,53,54,55,55,56,57,58,60,
     61,63,64,65,66,68,70,71,72,74,
     75,77,81,83,84,87,89,90,90,91
     ]
plt.style.use('ggplot')
plt.hist(x,bins=10)

plt.show()

import matplotlib.pyplot as plt
file=open('/content/drive/MyDrive/datasheet/salesdata2.csv - salesdata2.csv.csv','r')
data=file.readlines()
a_lst=[]
b_lst=[]

for handle in data:
  a,b=handle.split(sep=',')
  a_lst.append(int(a))
  b_lst.append(int(b))

plt.title("a vs b")
plt.xlabel("a")
plt.ylabel("b")
plt.scatter(a_lst,b_lst)
plt.show()